# CPSWatchdog Configuration
# Made by 3bdoabk

# CPS Thresholds
thresholds:
  # General CPS thresholds (applies to both left and right clicks)
  high_cps: 15.0        # CPS considered high/suspicious
  extreme_cps: 20.0     # CPS considered extremely suspicious
  violations_for_alert: 5  # Number of violations before major alert

  # Separate thresholds for left and right clicks (optional - if not set, uses general thresholds)
  left_click:
    high_cps: 15.0      # High threshold for left clicks (combat/mining)
    extreme_cps: 20.0   # Extreme threshold for left clicks
    enable_separate: false  # Set to true to use separate left click thresholds

  right_click:
    high_cps: 12.0      # High threshold for right clicks (interactions/building)
    extreme_cps: 18.0   # Extreme threshold for right clicks
    enable_separate: false  # Set to true to use separate right click thresholds

# Alert Settings
alerts:
  notify_staff: true          # Send alerts to staff members
  log_to_console: true        # Log alerts to console
  broadcast_extreme: false    # Broadcast extreme violations to all players

  # Alert message customization
  messages:
    left_click_alert: "&c[CPSWatchdog] &e{player} &fhas suspicious left click behavior: &c{reason}"
    right_click_alert: "&c[CPSWatchdog] &e{player} &fhas suspicious right click behavior: &c{reason}"
    combined_alert: "&c[CPSWatchdog] &e{player} &fhas suspicious click behavior: &c{reason}"

  # Sound alerts (requires compatible server version)
  sounds:
    enable_sounds: false
    high_cps_sound: "BLOCK_NOTE_BLOCK_PLING"
    extreme_cps_sound: "ENTITY_WITHER_SPAWN"

# Detection Settings
detection:
  consistency_check: true     # Check for bot-like consistency
  variance_threshold: 0.1     # Variance threshold for consistency detection
  minimum_clicks_for_analysis: 10  # Minimum clicks before analysis

  # Advanced detection settings
  advanced:
    # Pattern detection
    pattern_detection: true
    pattern_threshold: 0.95   # Threshold for detecting repetitive patterns

    # Burst detection
    burst_detection: true
    burst_threshold: 25.0     # CPS threshold for detecting click bursts
    burst_duration: 1000      # Maximum duration for a burst (ms)

    # Separate analysis for click types
    analyze_separately: true  # Analyze left and right clicks separately
    cross_click_analysis: false  # Check for coordinated left-right clicking patterns

# Data Management
data:
  cleanup_interval: 300000    # Clean up inactive player data (5 minutes in ms)
  session_timeout: 300000     # Time before player session expires (5 minutes in ms)

  # Storage settings
  storage:
    save_player_data: false   # Save player data to file (for persistence across restarts)
    data_retention_days: 7    # Days to keep player data (if saving enabled)
    auto_cleanup: true        # Automatically clean old data

# Performance Settings
performance:
  # Threading
  async_processing: false     # Process CPS calculations asynchronously (experimental)
  max_players_per_tick: 10    # Maximum players to process per server tick

  # Memory optimization
  optimize_memory: true       # Enable memory optimizations
  max_stored_clicks: 20       # Maximum clicks to store per player (for CPS calculation)