name: CPSWatchdog
version: '1.0'
main: dev.abdelrahmanmoharram.cpswatchdog.cpswatchdog
authors: [ 3bdoabk ]
website: https://abdelrahmanmoharram.vercel.app
api-version: 1.13
description: Advanced CPS monitoring and anti-cheat system

commands:
  cps:
    description: Check CPS of a player
    usage: /cps [player]
    permission: cpswatchdog.check
    aliases: [checkcps]
  cpsstats:
    description: View detailed CPS statistics
    usage: /cpsstats [player]
    permission: cpswatchdog.stats
    aliases: [cpsinfo]
  cpsalert:
    description: Toggle CPS alerts
    usage: /cpsalert
    permission: cpswatchdog.alert
    aliases: [cpsnotify]
  cpsreload:
    description: Reload plugin configuration
    usage: /cpsreload
    permission: cpswatchdog.reload
    aliases: [cpsrl]

permissions:
  cpswatchdog.*:
    description: Grants all CPSWatchdog permissions
    default: op
    children:
      cpswatchdog.check: true
      cpswatchdog.stats: true
      cpswatchdog.alert: true
      cpswatchdog.notify: true
      cpswatchdog.reload: true
  cpswatchdog.check:
    description: Allows checking CPS of players
    default: op
  cpswatchdog.stats:
    description: Allows viewing detailed CPS statistics
    default: op
  cpswatchdog.alert:
    description: Allows toggling CPS alerts
    default: op
  cpswatchdog.notify:
    description: Receives notifications about potential cheaters
    default: op
  cpswatchdog.reload:
    description: Allows reloading plugin configuration
    default: op